ALTER TABLE [kh184217].[CINEPLEX] DROP CONSTRAINT [FK__CINEPLEX__StoreI__61716316]
GO

ALTER TABLE [kh184217].[CINEPLEX] DROP CONSTRAINT [FK__CINEPLEX__Employ__6265874F]
GO

/****** Object:  Table [kh184217].[CINEPLEX]    Script Date: 5/10/2024 12:30:34 AM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[kh184217].[CINEPLEX]') AND type in (N'U'))
DROP TABLE [kh184217].[CINEPLEX]
GO

/****** Object:  Table [kh184217].[CINEPLEX]    Script Date: 5/10/2024 12:30:34 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [kh184217].[CINEPLEX](
	[CineplexID] [int] NOT NULL,
	[StoreID] [int] NOT NULL,
	[EmployeeID] [int] NULL,
	[Title] [varchar](255) NULL,
	[Date] [date] NULL,
	[Time] [time](7) NULL,
	[MPAA] [varchar](10) NULL,
	[HostName] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[CineplexID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [kh184217].[CINEPLEX]  WITH CHECK ADD FOREIGN KEY([EmployeeID])
REFERENCES [kh184217].[EMPLOYEE] ([EmployeeID])
GO

ALTER TABLE [kh184217].[CINEPLEX]  WITH CHECK ADD FOREIGN KEY([StoreID])
REFERENCES [kh184217].[STORE] ([StoreID])
GO

