/****** Object:  Table [kh184217].[CONCESSION]    Script Date: 5/10/2024 12:46:32 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [kh184217].[CONCESSION](
	[ItemID] [int] NOT NULL,
	[ConcessionType] [varchar](50) NULL,
	[ExpirationDate] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ItemID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [kh184217].[CONCESSION]  WITH CHECK ADD FOREIGN KEY([ItemID])
REFERENCES [kh184217].[ITEM] ([ItemID])
GO

ALTER TABLE [kh184217].[CONCESSION]  WITH CHECK ADD CHECK  (([ConcessionType]='Candy' OR [ConcessionType]='Drink' OR [ConcessionType]='Food'))
GO

