/****** Object:  Table [kh184217].[MERCH]    Script Date: 5/10/2024 12:49:06 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [kh184217].[MERCH](
	[ItemID] [int] NOT NULL,
	[MerchType] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ItemID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [kh184217].[MERCH]  WITH CHECK ADD FOREIGN KEY([ItemID])
REFERENCES [kh184217].[ITEM] ([ItemID])
GO

