/****** Object:  Table [kh184217].[MOVIE]    Script Date: 5/10/2024 12:49:24 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [kh184217].[MOVIE](
	[MovieID] [int] NOT NULL,
	[Title] [varchar](255) NULL,
	[YEAR] [int] NULL,
	[Genre] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[MovieID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

