/****** Object:  Table [kh184217].[RENTED]    Script Date: 5/10/2024 12:49:52 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [kh184217].[RENTED](
	[CustomerID] [int] NOT NULL,
	[EmployeeID] [int] NOT NULL,
	[MediaID] [int] NULL,
	[Title] [varchar](255) NULL,
	[DueDate] [date] NULL,
	[OverDue] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[CustomerID] ASC,
	[EmployeeID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [kh184217].[RENTED]  WITH CHECK ADD FOREIGN KEY([CustomerID])
REFERENCES [kh184217].[Customer_] ([CustomerID])
GO

ALTER TABLE [kh184217].[RENTED]  WITH CHECK ADD FOREIGN KEY([EmployeeID])
REFERENCES [kh184217].[EMPLOYEE] ([EmployeeID])
GO

ALTER TABLE [kh184217].[RENTED]  WITH CHECK ADD FOREIGN KEY([MediaID])
REFERENCES [kh184217].[MEDIATYPE] ([MediaID])
GO

ALTER TABLE [kh184217].[RENTED]  WITH CHECK ADD  CONSTRAINT [CHK_OverDue] CHECK  (([OverDue]=case when getdate()>[DueDate] then (1) else (0) end))
GO

ALTER TABLE [kh184217].[RENTED] CHECK CONSTRAINT [CHK_OverDue]
GO

