/****** Object:  Table [kh184217].[SHIRT]    Script Date: 5/10/2024 12:50:12 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [kh184217].[SHIRT](
	[ItemID] [int] NOT NULL,
	[Color] [varchar](50) NULL,
	[Material] [varchar](100) NULL,
	[Size] [varchar](3) NULL,
PRIMARY KEY CLUSTERED 
(
	[ItemID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [kh184217].[SHIRT]  WITH CHECK ADD FOREIGN KEY([ItemID])
REFERENCES [kh184217].[ITEM] ([ItemID])
GO

ALTER TABLE [kh184217].[SHIRT]  WITH CHECK ADD CHECK  (([Size]='XXL' OR [Size]='XL' OR [Size]='L' OR [Size]='M' OR [Size]='S' OR [Size]='XS' OR [Size]='XXS'))
GO

