/****** Object:  Table [kh184217].[WISHLIST]    Script Date: 5/10/2024 12:51:16 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [kh184217].[WISHLIST](
	[WishlistID] [int] NOT NULL,
	[CustomerID] [int] NULL,
	[TITLE] [varchar](255) NULL,
	[YEAR] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[WishlistID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [kh184217].[WISHLIST]  WITH CHECK ADD FOREIGN KEY([CustomerID])
REFERENCES [kh184217].[Customer_] ([CustomerID])
GO

